<?php declare(strict_types = 1);

namespace Tests\Toolkit;

use Contributte\Tester\Environment;
use Nette\Neon\Neon;

final class Helpers
{

	public static function createTestedFile(string $name): string
	{
		$neon = Neon::encode([
			'parameters' => [
				'database' => [
					'user' => 'bar',
					'pass' => 'bar',
					'dbname' => 'bar',
				],
				'mode' => 'bar',
			],
		], true);
		$content = '# This file is auto-generated by composer' . PHP_EOL . $neon;
		$fileName = Environment::getTestDir() . '/set_' . $name . '.neon';
		file_put_contents($fileName, $content);

		return $fileName;
	}

}
