<?php declare(strict_types = 1);

namespace Tests\Cases;

use Composer\IO\IOInterface;
use Contributte\Neonizer\Exception\Logical\InvalidArgumentException;
use Contributte\Neonizer\TaskSet;
use Contributte\Tester\Toolkit;
use Mockery;
use Nette\Neon\Neon;
use Tester\Assert;
use Tests\Toolkit\Helpers;

require_once __DIR__ . '/../bootstrap.php';

// testSetNoArgs
Toolkit::test(static function (): void {
	$io = Mockery::mock(IOInterface::class);
	$io->shouldReceive('write')
		->withArgs(['<error>Configuration file is required, e.q. -- $(pwd)/app/config/config.local.neon</error>'])
		->once()
		->getMock();

	$taskSet = new TaskSet($io);
	$taskSet->set([]);

	Assert::true(true);
});

// testSetNoParams
Toolkit::test(static function (): void {
	$io = Mockery::mock(IOInterface::class);
	$io->shouldReceive('write')
		->withArgs(['<error>Add some parameters, e.q. -- $(pwd)/app/config/config.local.neon --database.host=localhost --database.user=neonizer</error>'])
		->once()
		->getMock();

	$taskSet = new TaskSet($io);
	$taskSet->set([__DIR__ . '/../Fixtures/files/set.neon']);

	Assert::true(true);
});

// testSetInvalidArgument
Toolkit::test(static function (): void {
	$io = Mockery::mock(IOInterface::class);
	$taskSet = new TaskSet($io);

	Assert::throws(static function () use ($taskSet): void {
		$taskSet->set([
			__DIR__ . '/../Fixtures/files/set.neon',
			'invalid',
		]);
	}, InvalidArgumentException::class, 'Invalid argument "invalid" given.');
});

// testSetNoChange
Toolkit::test(static function (): void {
	$file = Helpers::createTestedFile('noChange');
	$expected = '# This file is auto-generated by composer' . PHP_EOL . Neon::encode([
			'parameters' => [
				'database' => [
					'user' => 'bar',
					'pass' => 'bar',
					'dbname' => 'bar',
				],
				'mode' => 'bar',
			],
		], true);

	$io = Mockery::mock(IOInterface::class);
	$io->shouldReceive('isInteractive')
		->andReturn(true)
		->getMock();

	$taskSet = new TaskSet($io);
	$taskSet->set([
		$file,
		'--database.user=bar',
	]);

	$actual = file_get_contents($file);
	Assert::same($expected, $actual);
});

// testSetChangeValue
Toolkit::test(static function (): void {
	$file = Helpers::createTestedFile('changeValue');
	$expected = '# This file is auto-generated by composer' . PHP_EOL . Neon::encode([
			'parameters' => [
				'database' => [
					'user' => 'foo',
					'pass' => 'bar',
					'dbname' => 'bar',
				],
				'mode' => 'bar',
			],
		], true);

	$io = Mockery::mock(IOInterface::class);
	$io->shouldReceive('isInteractive')
		->andReturn(true)
		->getMock();

	$taskSet = new TaskSet($io);
	$taskSet->set([
		$file,
		'--database.user=foo',
	]);

	$actual = file_get_contents($file);
	Assert::same($expected, $actual);
});

// testSetAddKey
Toolkit::test(static function (): void {
	$file = Helpers::createTestedFile('addKey');
	$expected = '# This file is auto-generated by composer' . PHP_EOL . Neon::encode([
			'parameters' => [
				'database' => [
					'host' => 'bar',
					'user' => 'bar',
					'pass' => 'bar',
					'dbname' => 'bar',
				],
				'mode' => 'bar',
			],
		], Neon::BLOCK);

	$io = Mockery::mock(IOInterface::class);
	$io->shouldReceive('isInteractive')
		->andReturn(true)
		->getMock();

	$taskSet = new TaskSet($io);
	$taskSet->set([
		$file,
		'--database.host=bar',
	]);

	$actual = file_get_contents($file);
	Assert::same($expected, $actual);
});

// testSetMultiple
Toolkit::test(static function (): void {
	$file = Helpers::createTestedFile('multiple');
	$expected = '# This file is auto-generated by composer' . PHP_EOL . Neon::encode([
			'parameters' => [
				'database' => [
					'host' => 'bar',
					'user' => 'foo',
					'pass' => 'bar',
					'dbname' => 'bar',
				],
				'mode' => 'bar',
			],
		], true);

	$io = Mockery::mock(IOInterface::class);
	$io->shouldReceive('isInteractive')
		->andReturn(true)
		->getMock();

	$taskSet = new TaskSet($io);
	$taskSet->set([
		$file,
		'--database.host=bar',
		'--database.user=foo',
	]);

	$actual = file_get_contents($file);
	Assert::same($expected, $actual);
});

// testBooleans
Toolkit::test(static function (): void {
	$file = Helpers::createTestedFile('booleans');
	$expected = '# This file is auto-generated by composer' . PHP_EOL . Neon::encode([
			'parameters' => [
				'database' => [
					'host' => true,
					'user' => false,
					'pass' => '1',
					'dbname' => '0',
				],
				'mode' => 'bar',
			],
		], true);

	$io = Mockery::mock(IOInterface::class);
	$io->shouldReceive('isInteractive')
		->andReturn(true)
		->getMock();

	$taskSet = new TaskSet($io);
	$taskSet->set([
		$file,
		'--database.host=true',
		'--database.user=false',
		'--database.pass=1',
		'--database.dbname=0',
	]);

	$actual = file_get_contents($file);
	Assert::same($expected, $actual);
});
