<?php

namespace Contributte\Neonizer\Encoder;

interface IEncoder
{

	const GENERATED_MESSAGE = 'This file is auto-generated by composer';

	/**
	 * @param mixed[] $value
	 * @return string|NULL
	 */
	public function encode($value);

}
