<?php declare(strict_types = 1);

namespace Contributte\Neonizer\Encoder;

interface IEncoder
{

	public const GENERATED_MESSAGE = 'This file is auto-generated by composer';

	/**
	 * @param mixed[] $value
	 */
	public function encode(array $value): ?string;

}
